#pragma once
#include <iostream>
#include <sstream>
#include <fstream>
#include <filesystem>
#include <random>
#include "Settings.h"

inline constexpr uint32_t GUID_STR_LENGTH = 36; // Length of the guid generated by GenerateGuid

namespace GuidUtils {
	// Returns a new randomized GUID
	inline std::string GenerateGuid()
	{
		thread_local std::random_device rd;
		thread_local std::mt19937_64 gen(rd());
		thread_local std::uniform_int_distribution<uint64_t> dis;

		uint64_t part1 = dis(gen);
		uint64_t part2 = dis(gen);

		uint8_t uuid[16];
		for (int i = 0; i < 8; i++) {
			uuid[i] = (part1 >> (i * 8)) & 0xFF;
		}
		for (int i = 0; i < 8; i++) {
			uuid[8 + i] = (part2 >> (i * 8)) & 0xFF;
		}

		uuid[6] = (uuid[6] & 0x0F) | 0x40;

		uuid[8] = (uuid[8] & 0x3F) | 0x80;

		std::stringstream ss;

		ss << std::hex << std::setfill('0');

		for (int i = 0; i < 16; i++) {
			ss << std::setw(2) << (int)uuid[i];
			if (i == 3 || i == 5 || i == 7 || i == 9) {
				ss << "-";
			}
		}

#ifdef DEBUG
			std::cout << "Generated GUID: " << ss.str() << std::endl;
#endif

		return ss.str();
	}

	// Gets the GUID of an asset if it has a corresponding .meta file
	// If no .meta file is found, it will be created and a new GUID will be written into it
	namespace fs = std::filesystem;
	inline bool GetOrGenerateGuid(const std::filesystem::path& assetPath, std::string& guid)
	{
		// Path validity checks
		if (!fs::is_regular_file(assetPath)) {
			std::cerr << "GuidUtils::GetOrGenerateGuid(): Asset is not a file" << std::endl;
			return false;
		}

		// Check if .meta file exists
		fs::path metaPath = assetPath;
		metaPath += ".meta";
		if (fs::is_regular_file(metaPath)) {
			// Read GUID from meta file
			std::ifstream in(metaPath);
			if (!in) {
				std::cerr << "GuidUtils::GetOrGenerateGuid(): Could not read meta file" << std::endl;
				return false;
			}

			std::string temp;
			if (in >> temp && !temp.empty()) {
				guid = temp;
				return true;
			}

			std::cerr << "GuidUtils::GetOrGenerateGuid(): Failed reading GUID from meta file. Generating new GUID in" << metaPath.filename() << std::endl;
		}

		// Generate meta file with a new GUID
		std::string newGuid = GenerateGuid();

		std::ofstream out(metaPath);
		if (!out) {
			std::cerr << "GuidUtils::GetOrGenerateGuid(): Could not create meta file" << std::endl;
			return false;
		}

		if (!(out << newGuid)) {
			std::cerr << "GuidUtils::GetOrGenerateGuid(): Could not write new guid to meta file" << std::endl;
			return false;
		}

		guid = newGuid;
		return true;
	}

	// Creates a .meta file for an asset with a predefined GUID
	inline bool CreateMetaFileFromGuid(const std::filesystem::path& assetPath, const std::string& guid) 
	{
		// Path validity checks
		if (!fs::is_regular_file(assetPath)) {
			std::cerr << "GuidUtils::GetOrGenerateGuid(): Asset is not a file" << std::endl;
			return false;
		}

		fs::path metaPath = assetPath;
		metaPath += ".meta";

		if (fs::is_regular_file(metaPath)) {
			std::cerr << "GuidUtils::GetOrGenerateGuid(): Meta file already exists" << std::endl;
			return false;
		}

		std::ofstream out(metaPath);
		if (!out) {
			std::cerr << "GuidUtils::GetOrGenerateGuid(): Cannot open meta file for writing" << std::endl;
			return false;
		}

		if (!(out << guid)) {
			std::cerr << "GuidUtils::GetOrGenerateGuid(): Cannot write GUID to meta file" << std::endl;
			return false;
		}

#ifdef DEBUG
			std::cout << "Created meta file for " << assetPath << std::endl;
#endif

		return true;
	}
}
